# Generated by Django 5.1.1 on 2024-10-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicted_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_etb_cgp', models.CharField(max_length=10, verbose_name='Wk/ETB CGP')),
                ('service', models.CharField(max_length=10)),
                ('vessel', models.CharField(max_length=100)),
                ('voyage_s', models.CharField(max_length=10, verbose_name='Voyage-S')),
                ('eta_cgp', models.DateField(verbose_name='ETA CGP')),
                ('etb_cgp', models.DateField(verbose_name='ETB CGP')),
                ('etd_cgp', models.DateField(verbose_name='ETD CGP')),
                ('voyage_n', models.CharField(max_length=10, verbose_name='Voyage-N')),
                ('eta_cmb', models.DateField(verbose_name='ETA CMB')),
                ('etb_cmb', models.DateField(verbose_name='ETB CMB')),
                ('etd_cmb', models.DateField(verbose_name='ETD CMB')),
                ('eta_cgp_2', models.DateField(verbose_name='ETA CGP-2')),
                ('etb_cgp_2', models.DateField(verbose_name='ETB CGP-2')),
                ('etd_cgp_2', models.DateField(verbose_name='ETD CGP-2')),
            ],
        ),
    ]
