# Generated by Django 5.1.1 on 2024-10-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
