# Generated by Django 5.1.1 on 2024-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0007_newitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_etb_cgp', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=10)),
                ('vessel', models.CharField(max_length=100)),
                ('voyage_s', models.CharField(max_length=10)),
                ('eta_cgp', models.DateField()),
                ('etb_cgp', models.DateField()),
                ('diff_eta_etb_cgp', models.IntegerField(blank=True, null=True)),
                ('etd_cgp', models.DateField()),
                ('diff_etb_etd_cgp', models.IntegerField(blank=True, null=True)),
                ('voyage_n', models.CharField(max_length=10)),
                ('eta_cmb', models.DateField()),
                ('diff_cgp_cmb', models.IntegerField(blank=True, null=True)),
                ('etb_cmb', models.DateField()),
                ('diff_eta_etb_cmb', models.IntegerField(blank=True, null=True)),
                ('etd_cmb', models.DateField()),
                ('diff_etb_etd_cmb', models.IntegerField(blank=True, null=True)),
                ('eta_cgp_2', models.DateField()),
                ('etb_cgp_2', models.DateField()),
                ('etd_cgp_2', models.DateField()),
            ],
        ),
    ]
