# Generated by Django 5.1.1 on 2024-10-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0008_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
