# Generated by Django 5.1.1 on 2024-10-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0009_delete_analysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewItem',
        ),
    ]
