# Generated by Django 5.1.1 on 2024-10-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0011_alter_analytics_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analytics',
            table='analytics',
        ),
    ]
