# Generated by Django 5.1.1 on 2024-11-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0012_alter_analytics_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCE_RV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_to_etb_cgp', models.IntegerField(default=1)),
                ('etb_to_etd_cgp', models.IntegerField(default=2)),
                ('cgp_to_cmb', models.IntegerField(default=5)),
                ('eta_to_etb_cmb', models.IntegerField(default=1)),
                ('etb_to_etd_cmb', models.IntegerField(default=2)),
                ('cmb_to_cgp', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='code',
        ),
        migrations.AddField(
            model_name='vessel',
            name='service',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='CCE_Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_model.vessel')),
            ],
        ),
    ]
