# Generated by Django 5.1.1 on 2024-11-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0013_cce_rv_remove_vessel_code_vessel_service_cce_vessel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cce_vessel',
            old_name='vessel',
            new_name='vessels',
        ),
    ]
