# Generated by Django 5.1.1 on 2024-11-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0014_rename_vessel_cce_vessel_vessels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CCE_Vessel',
        ),
    ]
