# Generated by Django 5.1.1 on 2024-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0015_delete_cce_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='previous_service',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='cgp_to_cmb',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='cmb_to_cgp',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='eta_to_etb_cgp',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='eta_to_etb_cmb',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='etb_to_etd_cgp',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='cce_rv',
            name='etb_to_etd_cmb',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
