# Generated by Django 5.1.1 on 2024-11-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0017_bes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BES_RV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_to_etb_cgp', models.IntegerField(blank=True, default=1, null=True)),
                ('etb_to_etd_cgp', models.IntegerField(blank=True, default=2, null=True)),
                ('cgp_to_sin', models.IntegerField(blank=True, default=5, null=True)),
                ('eta_to_etb_sin', models.IntegerField(blank=True, default=1, null=True)),
                ('etb_to_etd_sin', models.IntegerField(blank=True, default=2, null=True)),
                ('sin_to_pkg', models.IntegerField(blank=True, default=5, null=True)),
                ('eta_to_etb_pkg', models.IntegerField(blank=True, default=1, null=True)),
                ('etb_to_etd_pkg', models.IntegerField(blank=True, default=2, null=True)),
                ('pkg_to_cgp', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
    ]
