# Generated by Django 5.1.1 on 2024-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0018_bes_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='BES_Predicted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_etb_cgp', models.CharField(max_length=10, verbose_name='Wk/ETB CGP')),
                ('service', models.CharField(max_length=10)),
                ('vessel', models.CharField(max_length=100)),
                ('voyage_s', models.CharField(max_length=10, verbose_name='Voyage-S')),
                ('eta_cgp', models.DateField(verbose_name='ETA CGP')),
                ('etb_cgp', models.DateField(verbose_name='ETB CGP')),
                ('etd_cgp', models.DateField(verbose_name='ETD CGP')),
                ('voyage_n', models.CharField(max_length=10, verbose_name='Voyage-N')),
                ('eta_sin', models.DateField(verbose_name='ETA SIN')),
                ('etb_sin', models.DateField(verbose_name='ETB SIN')),
                ('etd_sin', models.DateField(verbose_name='ETD SIN')),
                ('eta_pkg', models.DateField(verbose_name='ETA PKG')),
                ('etb_pkg', models.DateField(verbose_name='ETB PKG')),
                ('etd_pkg', models.DateField(verbose_name='ETD PKG')),
                ('eta_cgp_2', models.DateField(verbose_name='ETA CGP-2')),
                ('etb_cgp_2', models.DateField(verbose_name='ETB CGP-2')),
                ('etd_cgp_2', models.DateField(verbose_name='ETD CGP-2')),
            ],
        ),
    ]
