# Generated by Django 5.1.1 on 2024-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0019_bes_predicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bes',
            name='voyage_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='voyage_complete',
            field=models.BooleanField(default=False),
        ),
    ]
