# Generated by Django 5.1.1 on 2024-11-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0021_bes_complete_cce_complete_vessel_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bes',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
