# Generated by Django 5.1.1 on 2024-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0023_rename_atb_cpg_bes_complete_atb_cgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bes_complete',
            name='only_vessel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='vessel_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='voyage_n',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voyage-N'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='voyage_n_with_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voyage-N with Code'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='voyage_s',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voyage-S'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='voyage_s_with_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voyage-S with Code'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='week_cgp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week CGP'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='week_cgp_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week CGP-2'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='week_pkg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week PKG'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='week_sin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week SIN'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='only_vessel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='vessel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='vessel_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='voyage_n',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voyage-N'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='voyage_n_with_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voyage-N with Code'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='voyage_s',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voyage-S'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='voyage_s_with_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voyage-S with Code'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='week_cgp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week CGP'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='week_cgp_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week CGP-2'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='week_cmb',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Week CMB'),
        ),
    ]
