# Generated by Django 5.1.1 on 2024-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0024_alter_bes_complete_only_vessel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bes_complete',
            name='berthing_delay_cpg',
        ),
        migrations.AddField(
            model_name='bes_complete',
            name='berthing_delay_cgp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='ata_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='ata_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP-2'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='ata_pkg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA PKG'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='ata_sin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA SIN'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atb_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATB CGP'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atb_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP-2'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atb_pkg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA PKG'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atb_sin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA SIN'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atd_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATD CGP'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atd_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATD CGP-2'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atd_pkg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATD PKG'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='atd_sin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATD SIN'),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='berth_delay_cgp_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='berthing_delay_pkg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bes_complete',
            name='berthing_delay_sin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
