# Generated by Django 5.1.1 on 2024-12-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0025_remove_bes_complete_berthing_delay_cpg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cce_complete',
            name='ata_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='ata_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP-2'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='ata_cmb',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CMB'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atb_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATB CGP'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atb_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP-2'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atb_cmb',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CMB'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atd_cgp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATD CGP'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atd_cgp_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CGP-2'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='atd_cmb',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ATA CMB'),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='berth_delay_cgp_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='berth_delay_cpg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cce_complete',
            name='berthing_delay_cmb',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
