# Generated by Django 5.1.1 on 2024-12-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0026_alter_cce_complete_ata_cgp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cce_complete',
            old_name='berth_delay_cpg',
            new_name='berth_delay_cgp',
        ),
    ]
