# Generated by Django 5.1.1 on 2024-12-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0027_rename_berth_delay_cpg_cce_complete_berth_delay_cgp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bes_complete',
            old_name='berth_delay_cgp_2',
            new_name='berthing_delay_cgp_2',
        ),
        migrations.RenameField(
            model_name='cce_complete',
            old_name='berth_delay_cgp',
            new_name='berthing_delay_cgp',
        ),
        migrations.RenameField(
            model_name='cce_complete',
            old_name='berth_delay_cgp_2',
            new_name='berthing_delay_cgp_2',
        ),
    ]
